### ISSUE TITLE
eval.py for the demo

### ISSUE THREAD

**Issue by duyguislakoglu** [autonomousvision/occupancy_flow#2]
Hello,
Great work!

I tried to run eval.py for the demo. Since in default.yaml, test:eval_mesh_iou is true, it does not initialize 'dataset' properly (Because data provided for demo does not contain points_seq). I solved this issue by adding test:eval_mesh_iou:false to demo.yaml.

Is there anything I am missing here?

Thank you,
Duygu

**Comment by m-niemeyer** [comment]
Hi @duyguislakoglu , Thanks a lot for you message and interest!

Yes, you are right. We added the demo data only for a short demonstration of the generation, not for evaluation.

For running the full evaluation, you would have to 

1. [Download and prepare the dataset](https://github.com/autonomousvision/occupancy_flow#dataset)
2. [Generate predicted data, e.g. with one of the pre-trained models](https://github.com/autonomousvision/occupancy_flow#generation)
3. [Call the evaluation function](https://github.com/autonomousvision/occupancy_flow#evaluation)

I hope this helps. Good luck with your research!

Best,
Michael

**Comment by duyguislakoglu** [comment]
You are right. Since I was not able to download the dataset (due to some OS related problems), I wanted to try it with demo. I will run the full evaluation when the dataset is ready.

Thank you for your reply,
Duygu
