### ISSUE TITLE
Training details

### ISSUE THREAD

**Issue by ray8828** [autonomousvision/occupancy_flow#3]
Hi, thanks for sharing your code!

I'm training O-Flow as a comparison, what's the total training epoch/iteration for D-FAUST point cloud completion? Thanks

**Comment by m-niemeyer** [comment]
Hi @ray8828 , thanks for your interest in the project!

We trained it for quite some time and then in the code, automatically the "model_best" is selected which is the model which performs best on the validation metric. We trained the models for at least roughly 100 epochs. 

Good luck with your research!
