### ISSUE TITLE
visualization code

### ISSUE THREAD

**Issue by jason718** [autonomousvision/occupancy_flow#4]
Thanks for the amazing work!

Is it possible to share the vis code of the nice figures (*.gif) as bellow?

![field_jumping_jacks](https://user-images.githubusercontent.com/3235510/109088741-a0a1c500-76d5-11eb-84bd-93ae2bdaffeb.gif)

**Comment by m-niemeyer** [comment]
Hi @jason718 , thanks a lot for your interest in the project!

Sadly we do not share the script for this, but you can play around with the[ mayavi library](https://docs.enthought.com/mayavi/mayavi/) which is easy to use and has some cool features!
