### ISSUE TITLE
Demo fails

### ISSUE THREAD

**Issue by MasahiroOgawa** [autonomousvision/occupancy_flow#8]
I tried to run demo, but it failed with this error;
```
    from .pykdtree.kdtree import KDTree
  File "__init__.pxd", line 885, in init pykdtree.kdtree
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
```

**Comment by MasahiroOgawa** [comment]
Probably this is caused by numpy version <ref>(https://github.com/automl/auto-sklearn/issues/621).
I will try to fix this.

**Comment by MasahiroOgawa** [comment]
Finally I solve the problem using docker environment.
See https://github.com/autonomousvision/occupancy_flow/pull/9

**Comment by MasahiroOgawa** [comment]
Actually it worked on GTX1060, but it failed on GTX3070.
But finally I fixed it and confirmed to finish demo even native (witout docker environment).
I updated the pull request.
So please check the above #9 pull request.

**Comment by m-niemeyer** [comment]
Thanks @MasahiroOgawa for creating the respective docker environment - I merged your pull request now!
